version: '3'

networks:
  web:
    external: true

services:
  inspire:
    restart: always
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
    image: ijpatricio/Inspire:${TAG:-latest}
    volumes:
      - ./.env:/var/www/html/.env
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.Inspire.entrypoints=https
      - traefik.http.routers.Inspire.rule=Host(`${TRAEFIK_HOST:-inspire.jpat.dev}`)
      - traefik.http.routers.Inspire.service=Inspire
      - traefik.http.services.Inspire.loadbalancer.server.port=80
      - traefik.http.routers.Inspire.tls.certresolver=leresolver
